version: '3.8'

services:
  postgres:
    image: postgres:16.3
    container_name: chromia_android_db
    environment:
      POSTGRES_DB: postchain
      POSTGRES_USER: postchain
      POSTGRES_PASSWORD: postchain
      POSTGRES_INITDB_ARGS: "--locale=C.UTF-8 --encoding=UTF8"
    ports:
      - "5432:5432"
    volumes:
      - chromia_postgres_data:/var/lib/postgresql/data

volumes:
  chromia_postgres_data: 