name: Generate Summary

on:
  workflow_run:
    workflows:
      - Android CI
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download test results artifact
      uses: actions/download-artifact@v3
      with:
        name: test-results

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: python -m pip install --upgrade pip

    - name: Generate summary
      run: |
        python file_summary.py
        cat test-results/testresults.txt >> summary.txt

    - name: Commit and push summary
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add summary.txt
        git commit -m "Update summary.txt with test results"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
